baseURL = "https://stop-frelons.netlify.com/"
languageCode = "en-us"
title = "Stop-Frelons"
theme = "sftheme"

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = -110
  [[menu.main]]
    name = "Conseils"
    url = "/conseils/"
    weight = -100
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = -100
  [[menu.main]]
    name = "Zones d'Interventions"
    url = "/zones-d-interventions/"
    weight = -100

  [[menu.mainb]]
 	identifier = "leFrelon"
    name = "Le Frelon"
    url = "/le-frelon"
    post = "<i class='mdi mdi-chevron-down'></i>"
    weight = 1 
  [[menu.mainb]]
  	parent = "leFrelon"
  	identifier = "leFrelonSub1"
    name = "Histoire du Frelon"
    url = "/le-frelon/histoire-du-frelon-asiatique"
  [[menu.mainb]]
  	parent = "leFrelon"
  	identifier = "leFrelonSub3"
    name = "Livres spécialisés"
    url = "/le-frelon/livres-specialises"
  [[menu.mainb]]
  	parent = "leFrelon"
  	identifier = "leFrelonSub2"
    name = "Quelques chiffres"
    url = "/le-frelon/quelques-chiffres"
  [[menu.mainb]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3 
  [[menu.mainb]]
    name = "Contact"
    url = "/contact/"
    weight = 4
